name: Desplegar Portafolio a GitHub Pages

on:
  push:
    branches: [main] # Se ejecutará cada vez que subas código a la rama main

# Permisos mínimos necesarios para que el bot pueda publicar en Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Compilar Proyecto
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Instalar Dependencias
        run: pnpm install --frozen-lockfile

      - name: Compilar Sitio Estático
        run: pnpm run build

      - name: Subir Artefacto de Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    name: Desplegar en Producción
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
